# Generated by Django 2.0.5 on 2018-05-08 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alluser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='user_pictures')),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('residential_location', models.CharField(max_length=30)),
                ('housing_condition', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('evaluation', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('breed', models.CharField(max_length=20)),
                ('character', models.CharField(max_length=200)),
                ('is_foster', models.BooleanField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Alluser')),
            ],
        ),
    ]
