# Generated by Django 2.0.5 on 2018-05-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='equipment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='evaluation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='housing_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='picture',
            field=models.ImageField(blank=True, upload_to='user_pictures'),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='residential_location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
