# Generated by Django 2.0.5 on 2018-05-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20180510_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='residential_location',
            field=models.CharField(max_length=30),
        ),
    ]
