# Generated by Django 2.0.5 on 2018-05-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_dogs_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Dogs')),
            ],
        ),
    ]
