# Generated by Django 2.0.5 on 2018-05-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_gpss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpss',
            name='latitude',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='gpss',
            name='longitude',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
