# Generated by Django 2.0.5 on 2018-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20180523_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpss',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gpss',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
