# Generated by Django 2.0.5 on 2018-05-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
