# Generated by Django 2.0.5 on 2018-05-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20180527_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='is_foster',
            field=models.BooleanField(default=False),
        ),
    ]
