# Generated by Django 2.0.5 on 2018-05-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20180528_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='collection_user',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
