# Generated by Django 2.0.5 on 2018-06-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_alluser_collection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='chat_user',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
