# Generated by Django 2.0.5 on 2018-06-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_auto_20180605_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='測試帳號', max_length=20),
            preserve_default=False,
        ),
    ]
