# Generated by Django 2.0.5 on 2018-06-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_auto_20180605_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='introduce',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
