# Generated by Django 2.0.5 on 2018-06-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_auto_20180606_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='size',
        ),
    ]
