# Generated by Django 2.0.5 on 2018-06-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_auto_20180613_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keym',
            name='account',
        ),
    ]
