# Generated by Django 2.0.5 on 2018-06-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0026_remove_keym_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='character',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='keym',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='keym',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Alluser'),
        ),
    ]
