# Generated by Django 2.0.5 on 2018-06-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0027_auto_20180613_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keym',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keym',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Alluser'),
        ),
    ]
