# Generated by Django 2.0.5 on 2018-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0028_auto_20180613_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keym',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
