# Generated by Django 2.0.5 on 2018-06-14 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_auto_20180613_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=30)),
                ('employee', models.CharField(max_length=30)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('note', models.CharField(max_length=300)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Dogs')),
            ],
        ),
    ]
