# Generated by Django 2.0.5 on 2018-06-14 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0030_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='stores.Alluser'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userr', to='stores.Alluser'),
        ),
    ]
