# Generated by Django 2.0.5 on 2018-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0033_auto_20180614_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keym',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
